### PR TITLE
More Links (sorry)

### PR DESCRIPTION
**Pull request by techguy16**
Don't merge this just yet - I'm adding more links.
I'll `@` you when it's done.

### CODE REVIEW

**Comment by elbkr** [comment]
Should I merge it?

**Comment by elbkr** [comment]
Also you can't change the readme, you should revert the change you made.

**Comment by techguy16** [comment]
@elbkr Just adding all the links to websites.json and then you can merge it :)

**Comment by techguy16** [comment]
@elbkr :+1:

**Comment by elbkr** [comment]
Merging, thanks ^^

**Comment by techguy16** [comment]
I'm sorry for almost 1000 urls, I just had to do it due to the surge in Tesla scams.

**Pull request merged**
